### ISSUE TITLE
Location for models and datasets

### ISSUE THREAD

**Issue by surfingnirvana** [SHI-Labs/Cross-Scale-Non-Local-Attention#4]
Where do i have to put the models and the dataset folders?

**Comment by HarukiYqM** [comment]
> Where do i have to put the models and the dataset folders?

Hi, you can put the datasets to anywhere you like and then specify the data_dir in the options.py to that directory, e.g., create a  folder “data” and then put DIV2K and benchmark datasets into that folder and set the data_dir argument as the path to “data”. Similarly, you can also put the models to anywhere you like and set the pre_trained as the path to the models.

**Comment by JustinAsdz** [comment]
Hi Thanks for your work 

New to this area, And wonder ask why I have copied 800 images to  ../../DIV2K/bin/DIV2K_train/  ,but the **training codes returns got no samples** as follows,  can you tell me what should I do , Thanks
`
Traceback (most recent call last):
  File "main.py", line 39, in <module>    main()
  File "main.py", line 27, in main    loader = data.Data(args)
  File "/mnt/data0/home/***/SR/csnln/Cross-Scale-Non-Local-Attention-master/src/data/__init__.py", line 35, in __init__
    num_workers=args.n_threads,
  File "/mnt/data0/home/***/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 224, in __init__
    sampler = RandomSampler(dataset, generator=generator)
  File "/mnt/data0/home/***/miniconda3/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 96, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
`

And by the way, Can you explain how you **generate your LR dataset**, using matlab or np.imresize? 

Thanks

**Comment by JustinAsdz** [comment]
> Hi Thanks for your work
> 
> New to this area, And wonder ask why I have copied 800 images to ../../DIV2K/bin/DIV2K_train/ ,but the **training codes returns got no samples** as follows, can you tell me what should I do , Thanks
> `Traceback (most recent call last): File "main.py", line 39, in <module> main() File "main.py", line 27, in main loader = data.Data(args) File "/mnt/data0/home/***/SR/csnln/Cross-Scale-Non-Local-Attention-master/src/data/__init__.py", line 35, in __init__ num_workers=args.n_threads, File "/mnt/data0/home/***/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 224, in __init__ sampler = RandomSampler(dataset, generator=generator) File "/mnt/data0/home/***/miniconda3/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 96, in __init__ "value, but got num_samples={}".format(self.num_samples)) ValueError: num_samples should be a positive integer value, but got num_samples=0`
> 
> And by the way, Can you explain how you **generate your LR dataset**, using matlab or np.imresize?
> 
> Thanks

Solved by move the original file out of directory ../../bin/
According to the following codes
![image](https://user-images.githubusercontent.com/38929721/99898721-a787f880-2cde-11eb-9eab-4e3e32062d21.png)

And the program will automatically generate binary file based on the jpeg or png  file .

But Encounter the Error: 
`FileNotFoundError: No such file: '/mnt/data0/home/***/SR/csnln/DIV2K/DIV2K_train_LR_bicubic/X2/0001x2.png' `
For I've not generate the LR imgs.
**Can you tell How you prepare the LR imgs?**

**Comment by lidong-pig** [comment]
> 

您好，请问我将div2k放在src/model中，那我的data_dir默认的应该是'../src/model'吗？

**Comment by lidong-pig** [comment]
楼主您好，我也是同样的问题。dir-data设置是div2k训练集的路径吗？那这运行的产生的div2k/bin/div2k_train_hr是干嘛的？是将800张训练样本放进去吗？ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by lidong-pig** [comment]
hello! i have a same quession.first，i set the dir_data to‘../src/model/DIV2K’.then run the main.py .it create DIV2K/bin/DIV2K_train_hr. At the same time,it tell me :ValueError: num_samples should be a positive integer value, but got num_samples=0 so what i will do?  should i copy 800 images to ../../DIV2K/bin/DIV2K_train/?

**Comment by lidong-pig** [comment]
> > 嗨谢谢你的工作
> > 这个领域的新手，想知道为什么我将800张图像复制到../../DIV2K/bin/DIV2K_train/，但是**训练代码返回没有样本**如下，你能告诉我我该怎么办，谢谢
> > `Traceback (most recent call last): File "main.py", line 39, in <module> main() File "main.py", line 27, in main loader = data.Data(args) File "/mnt/data0/home/***/SR/csnln/Cross-Scale-Non-Local-Attention-master/src/data/__init__.py", line 35, in __init__ num_workers=args.n_threads, File "/mnt/data0/home/***/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 224, in __init__ sampler = RandomSampler(dataset, generator=generator) File "/mnt/data0/home/***/miniconda3/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 96, in __init__ "value, but got num_samples={}".format(self.num_samples)) ValueError: num_samples should be a positive integer value, but got num_samples=0`
> > 顺便说一下，你能解释一下如何使用 matlab 或 np.imresize**生成 LR 数据集吗？**
> > 谢谢
> 
> 将原文件移出目录 ../../bin/ 解决 根据以下代码 ![图片](https://user-images.githubusercontent.com/38929721/99898721-a787f880-2cde-11eb-9eab-4e3e32062d21.png)
> 
> 并且程序会根据jpeg或png文件自动生成二进制文件。
> 
> 但是遇到错误： `FileNotFoundError: No such file: '/mnt/data0/home/***/SR/csnln/DIV2K/DIV2K_train_LR_bicubic/X2/0001x2.png' ` 因为我没有生成 LR imgs。 **你能告诉你如何准备LR imgs吗？**

hi，you have got it？i meet the same question. can you tell me. thanks!

**Comment by Ralapfranco** [comment]
> > 嗨谢谢你的工作
> > 这个领域的新手，想知道为什么我将800张图像复制到../../DIV2K/bin/DIV2K_train/，但是**训练代码返回没有样本**如下，你能告诉我我该怎么办，谢谢
> > `Traceback (most recent call last): File "main.py", line 39, in <module> main() File "main.py", line 27, in main loader = data.Data(args) File "/mnt/data0/home/***/SR/csnln/Cross-Scale-Non-Local-Attention-master/src/data/__init__.py", line 35, in __init__ num_workers=args.n_threads, File "/mnt/data0/home/***/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 224, in __init__ sampler = RandomSampler(dataset, generator=generator) File "/mnt/data0/home/***/miniconda3/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 96, in __init__ "value, but got num_samples={}".format(self.num_samples)) ValueError: num_samples should be a positive integer value, but got num_samples=0`
> > 顺便说一下，你能解释一下如何使用 matlab 或 np.imresize**生成 LR 数据集吗？**
> > 谢谢
> 
> 将原文件移出目录 ../../bin/ 解决 根据以下代码 ![图片](https://user-images.githubusercontent.com/38929721/99898721-a787f880-2cde-11eb-9eab-4e3e32062d21.png)
> 
> 并且程序会根据jpeg或png文件自动生成二进制文件。
> 
> 但是遇到错误： `FileNotFoundError: No such file: '/mnt/data0/home/***/SR/csnln/DIV2K/DIV2K_train_LR_bicubic/X2/0001x2.png' ` 因为我没有生成 LR imgs。 **你能告诉你如何准备LR imgs吗？**

me too！ you can down the X2 LR
